#!/usr/bin/env python3
"""
New Project Reset Script — prepares the template for a fresh project.

Usage:
    python scripts/new_project.py

What it does:
    1. Prompts for the new project name
    2. Resets all docs/project/config/ files to blank templates
    3. Resets workflow/ living documents (ADR, ERRORS) to blank templates
    4. Resets docs/project/config/epics/ (clears epic folders, keeps structure)
    5. Resets docs/project/testing/BLIND_SCENARIOS.md to blank template
    6. Prints a summary of everything that was reset
"""

import os
import shutil
import sys
from pathlib import Path

# --- Constants ---

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = PROJECT_ROOT / "docs" / "project" / "config"
EPICS_DIR = CONFIG_DIR / "epics"
WORKFLOW_DIR = PROJECT_ROOT / "workflow"
TESTING_DIR = PROJECT_ROOT / "docs" / "project" / "testing"

# --- Template contents for config files ---

CONFIG_TEMPLATES = {
    "brainstorm.md": (
        "# Brainstorm — Project-Specific Output\n"
        "> Generated by following `docs/project/requirements/1-BRAINSTORM.md`\n"
        "\n"
        "<!-- Fill this in when running Stage 1 -->\n"
    ),
    "prd.md": (
        "# Product Requirements Document — Project-Specific Output\n"
        "> Generated by following `docs/project/requirements/2-PRD.md`\n"
        "\n"
        "<!-- Fill this in when running Stage 2 -->\n"
    ),
    "architecture.md": (
        "# Architecture — Project-Specific Output\n"
        "> Generated by following `docs/project/requirements/3-ARCHITECTURE.md`\n"
        "\n"
        "<!-- Fill this in when running Stage 3 -->\n"
    ),
    "logging.md": (
        "# Logging Setup — Project-Specific Output\n"
        "> Generated by following `docs/project/requirements/4-LOGGING.md`\n"
        "\n"
        "<!-- Fill this in when running Stage 4 -->\n"
    ),
    "build-log.md": (
        "# Build Log — Session History\n"
        "> Generated by following `docs/project/requirements/6-BUILD.md`\n"
        "\n"
        "<!-- Add session entries here as you build -->\n"
    ),
    "codebase.md": (
        "# Codebase Documentation — Project-Specific Output\n"
        "> Generated by following `docs/project/requirements/7-CODEBASE.md`\n"
        "\n"
        "<!-- Document actual modules, dependencies, and technical debt here -->\n"
    ),
}

EPICS_TEMPLATES = {
    "ACTIVE.md": (
        "# Active Context\n"
        "\n"
        "## Current Sprint\n"
        "- **Story:** [none yet]\n"
        "- **File:** [link to story file]\n"
        "- **Goal:** [one-line goal]\n"
        "- **Modules touched:** [list]\n"
        "\n"
        "## Completed\n"
        "<!-- Move finished stories here -->\n"
    ),
    "overview.md": (
        "# Epic Overview\n"
        "> Generated by following `docs/project/requirements/5-EPICS.md`\n"
        "\n"
        "| ID | Epic | Status | Stories |\n"
        "|---|---|---|---|\n"
        "| EPIC-1 | [name] | [ ] | |\n"
        "| EPIC-2 | [name] | [ ] | |\n"
        "\n"
        "<!-- Add epics as they are defined. Create a folder per epic "
        "(epic-1/, epic-2/) with one story file per story. -->\n"
    ),
}

# --- Template contents for workflow files ---

ADR_TEMPLATE = """\
# Architecture Decision Records (ADR)

## TL;DR
- Log every significant technical decision here (if wrong = 2+ hours to undo)
- Check this BEFORE making architectural changes — don't contradict past decisions
- Never delete/modify entries — append only
- To override a past decision: add a new ADR referencing the old one

---

## ADR Index
| ID | Title | Status | Date | Epic |
|---|---|---|---|---|
| ADR-001 | [Decision title] | Accepted / Superseded | [DATE] | EPIC-X |

---

## ADR Template
> Copy this block for each new decision. One ADR per significant choice.
> What counts as "significant"? If getting it wrong would cost more than 2 hours to undo — write an ADR.

---

### ADR-001: [Decision Title]
**Date:** [DATE]
**Epic / Story:** EPIC-X / Story X.Y
**Status:** `Proposed` → `Accepted` → `Superseded by ADR-XXX`
**Decided by:** [Human / AI / Both]

#### Context
> What situation forced this decision? What constraints existed?

[Describe the context in 2-4 sentences.]

#### Decision
> What was decided? State it clearly and unambiguously.

**We will [do X] using [approach Y].**

#### Alternatives Considered
| Option | Pros | Cons | Reason Rejected |
|---|---|---|---|
| [Option A — chosen] | [pros] | [cons] | *Chosen* |
| [Option B] | [pros] | [cons] | [Why rejected] |

#### Consequences
**Positive:**
- [What this decision enables or improves]

**Negative / Trade-offs:**
- [What this decision constrains or makes harder]

**What this decision affects:**
- Files: `src/[file]`
- Modules: [which modules are shaped by this choice]

#### Review Triggers
- [ ] If [condition]

---

## 📌 Superseded Decisions
| Superseded ADR | Superseded By | Date | Reason |
|---|---|---|---|
"""

ERRORS_TEMPLATE = """\
# Known Errors & Investigation Methodology

## TL;DR
1. **Check the Error Registry below** — has this been solved before?
2. **Simplify before complexifying** — minimal fix first, test, then add complexity
3. **Compare with existing code** — copy working patterns, don't invent new ones
4. **Test after every change** — one change at a time, verify each
5. **If stuck** — STOP, restore to working state, restart simpler
6. **After fixing** — add an entry to the Error Registry immediately

---

## 🔍 Investigation Methodology

> **Read this BEFORE attempting to fix ANY error.**

### Fundamental Principles

#### 1. Simplify BEFORE Complexifying
- ❌ **BAD:** Add complex solutions
- ✅ **GOOD:** Create a minimal working version first

#### 2. Compare With Existing Code
- ❌ **BAD:** Create new code without looking at how it's done elsewhere
- ✅ **GOOD:** Find similar examples in the codebase, copy the working pattern

#### 3. Test Progressively
- ❌ **BAD:** Create everything at once, test only at the end
- ✅ **GOOD:** Create one thing at a time, test after each addition

#### 4. Isolate the Problem
- ❌ **BAD:** Modify several things at the same time
- ✅ **GOOD:** Test if the problem existed before your changes

#### 5. Don't Break the Application
- ❌ **BAD:** Keep modifying even if the app no longer works
- ✅ **GOOD:** Restore immediately if the app is broken

### Checklist Before Modifying Code
- [ ] I've read the existing code to understand the pattern
- [ ] I've found similar examples in the codebase
- [ ] I will create a minimal version first
- [ ] I will test after each modification
- [ ] I know how to restore if it breaks
- [ ] I will NOT add unnecessary complexity

---

## Error Registry

## Error Index
| ID | Category | Short Description | Status | First Seen | Epic |
|---|---|---|---|---|---|

---

## Error Categories
- **DATA** — ingestion, parsing, schema, quality issues
- **CONFIG** — missing env vars, bad config values
- **INTEGRATION** — API failures, DB connection errors
- **LOGIC** — incorrect calculations, wrong business logic
- **PERFORMANCE** — timeouts, memory issues, slow queries
- **DEPENDENCY** — package conflicts, version mismatches
- **INFRA** — deployment, environment, path issues
- **UI** — frontend rendering, state management

---

## Error Entries

### ERR-001: [Short Title]
**Category:** [DATA / CONFIG / INTEGRATION / LOGIC / PERFORMANCE / DEPENDENCY / INFRA / UI]
**Status:** `Open` → `Resolved` → `Recurring`
**First seen:** [DATE] — EPIC-X / Story X.Y

#### Symptoms
```
[Paste the exact error message]
```

#### Root Cause
[Explain the root cause clearly.]

#### Fix Applied
**Date fixed:** [DATE]
**Commit:** `[hash]`

#### Prevention Rule
> 🔒 **RULE ERR-001:** [Write the rule as a clear instruction]

#### Test Added
- [ ] Regression test added: `tests/dev/test_[module].py::test_[name]`

---

## 🔒 Prevention Rules Summary
| Rule ID | Applies To | Rule |
|---|---|---|

---

## 📊 Error Patterns
| Pattern | Count | Root Cause Theme | Systemic Fix |
|---|---|---|---|
"""

BLIND_SCENARIOS_TEMPLATE = """\
# 🔒 Blind Test Scenarios
> **SEALED DURING DEVELOPMENT**
> This file is written at PRD stage and NOT touched until dev is complete.
> The AI is explicitly forbidden from reading this file during development (see `CLAUDE.md`).
> Run these ONLY after `docs/5-BUILD.md` Definition of Done checklist is fully checked.

---

## How to Run Blind Scenarios
1. Confirm `docs/5-BUILD.md` DoD checklist is complete
2. Read each scenario below cold — do not pre-test
3. Run each scenario manually or via the automated runner
4. Record results in the Results table at the bottom
5. Any FAIL is a real bug — fix it and re-run all scenarios

---

## 📝 Scenario Authorship
These scenarios were written by:
- [ ] **Human** (at PRD stage)
- [ ] **AI pass** (Claude, after PRD was locked, before dev started)

---

## HUMAN-WRITTEN SCENARIOS

### H-SCN-01: [Scenario Name]
**Category:** [Edge Case / Error Handling / Performance / Security / Data Quality]
**Trigger:** [What action or input initiates this scenario]
**Setup:** [Any data or state needed]
**Steps:**
1.
**Expected Result:** [What SHOULD happen]
**Why it's interesting:** [Why you think this might break things]

---

## AI-GENERATED SCENARIOS

### A-SCN-01: [AI writes this at PRD stage]
**Category:**
**Trigger:**
**Setup:**
**Steps:**
1.
**Expected Result:**
**Reasoning:** [Why Claude thinks this is a risk]

---

## 📊 Results Log
| Scenario | Date Run | Result | Notes | Fixed? |
|---|---|---|---|---|

---

## 🏁 Blind Test Sign-Off
```
All scenarios passed:    [ ] Yes  [ ] No — [N] failures remaining
Sign-off date:
Notes:
```
"""


def reset_config_files() -> list[str]:
    """Reset all docs/project/config/ files to blank templates."""
    reset_files = []
    for filename, content in CONFIG_TEMPLATES.items():
        filepath = CONFIG_DIR / filename
        filepath.write_text(content)
        reset_files.append(str(filepath.relative_to(PROJECT_ROOT)))
    return reset_files


def reset_epics_dir() -> list[str]:
    """Reset epics directory — remove epic folders, reset template files."""
    reset_files = []

    # Remove all epic-X/ subdirectories
    if EPICS_DIR.exists():
        for item in EPICS_DIR.iterdir():
            if item.is_dir() and item.name.startswith("epic-"):
                shutil.rmtree(item)
                reset_files.append(f"🗑️  Removed {item.relative_to(PROJECT_ROOT)}/")

    # Create epic-1/ with a blank story template
    epic_1_dir = EPICS_DIR / "epic-1"
    epic_1_dir.mkdir(parents=True, exist_ok=True)
    story_template = (
        "# Story 1.1 — [Title]\n"
        "\n"
        "## Goal\n"
        "[One-line goal]\n"
        "\n"
        "## Acceptance Criteria\n"
        "- [ ] Criterion 1\n"
        "- [ ] Criterion 2\n"
        "\n"
        "## Tasks\n"
        "- [ ] Task 1\n"
        "- [ ] Task 2\n"
        "\n"
        "## Status: `pending`\n"
    )
    story_path = epic_1_dir / "story-1.1.md"
    story_path.write_text(story_template)
    reset_files.append(str(story_path.relative_to(PROJECT_ROOT)))

    # Reset ACTIVE.md and overview.md
    for filename, content in EPICS_TEMPLATES.items():
        filepath = EPICS_DIR / filename
        filepath.write_text(content)
        reset_files.append(str(filepath.relative_to(PROJECT_ROOT)))

    return reset_files


def reset_workflow_files() -> list[str]:
    """Reset workflow living documents to blank templates."""
    reset_files = []

    files_and_templates = {
        "ADR.md": ADR_TEMPLATE,
        "ERRORS.md": ERRORS_TEMPLATE,
    }

    for filename, content in files_and_templates.items():
        filepath = WORKFLOW_DIR / filename
        filepath.write_text(content)
        reset_files.append(str(filepath.relative_to(PROJECT_ROOT)))

    return reset_files


def reset_blind_scenarios() -> list[str]:
    """Reset blind test scenarios to blank template."""
    filepath = TESTING_DIR / "BLIND_SCENARIOS.md"
    TESTING_DIR.mkdir(parents=True, exist_ok=True)
    filepath.write_text(BLIND_SCENARIOS_TEMPLATE)
    return [str(filepath.relative_to(PROJECT_ROOT))]


def main() -> None:
    """Run the full project reset."""
    print("=" * 60)
    print("🆕  NEW PROJECT SETUP")
    print("=" * 60)
    print()

    # Prompt for project name
    project_name = input("Enter the new project name (or press Enter to skip): ").strip()
    if not project_name:
        project_name = "[unnamed project]"

    print()
    print(f"📋 Project: {project_name}")
    print(f"📁 Root: {PROJECT_ROOT}")
    print()

    # Confirm before proceeding
    confirm = input("⚠️  This will reset ALL config and workflow files. Continue? (y/n): ").strip().lower()
    if confirm != "y":
        print("❌ Aborted.")
        sys.exit(0)

    print()
    all_reset = []

    # Step 1: Config files
    print("📄 Resetting config files...")
    all_reset.extend(reset_config_files())

    # Step 2: Epics directory
    print("📂 Resetting epics directory...")
    all_reset.extend(reset_epics_dir())

    # Step 3: Workflow files
    print("🔧 Resetting workflow files...")
    all_reset.extend(reset_workflow_files())

    # Step 4: Blind scenarios
    print("🧪 Resetting blind test scenarios...")
    all_reset.extend(reset_blind_scenarios())

    # Summary
    print()
    print("=" * 60)
    print("✅  RESET COMPLETE")
    print("=" * 60)
    print()
    print("Files reset:")
    for f in all_reset:
        print(f"  ✓ {f}")
    print()
    print("📋 Next steps:")
    print("  1. Open docs/project/requirements/REQUIREMENTS_WORKFLOW.md")
    print("  2. Start with 1-BRAINSTORM.md")
    print("  3. Follow stages 1 → 7 sequentially")
    print()
    print(f"🚀 Good luck with '{project_name}'!")


if __name__ == "__main__":
    main()
